/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static javax.security.auth.callback.ConfirmationCallback.INFORMATION;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Gilberto
 */
public class LoginView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());

    /**
     * Creates new form LoginView
     */
    private int intentos = 0;
    private boolean passwordVisible = false;

    public LoginView() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/icons/coding.png")).getImage());
        this.setTitle("Login de Programas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jInicioLabel = new javax.swing.JLabel();
        jInicioLabel2 = new javax.swing.JLabel();
        jUsernameLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        jIngresarBtn = new javax.swing.JButton();
        jCancelarBtn = new javax.swing.JButton();
        jViewPasswordBtn = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        jProgressBar = new javax.swing.JProgressBar();
        jMenLabel = new javax.swing.JLabel();
        jKeyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInicioLabel.setBackground(new java.awt.Color(255, 255, 255));
        jInicioLabel.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jInicioLabel.setForeground(new java.awt.Color(255, 255, 255));
        jInicioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicioLabel.setText("¡Bienvenido!");
        jPanel2.add(jInicioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 30));

        jInicioLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jInicioLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jInicioLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInicioLabel2.setText("Inicio de Sesion.");
        jPanel2.add(jInicioLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));

        jUsernameLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel.setText("USUARIO");
        jPanel1.add(jUsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 92, 100, 30));

        jPasswordLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordLabel.setText("CONTRASEÑA");
        jPanel1.add(jPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 130, 30));

        jUsernameField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPanel1.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 440, 40));

        jIngresarBtn.setBackground(new java.awt.Color(51, 153, 255));
        jIngresarBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jIngresarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jIngresarBtn.setText("Ingresar");
        jIngresarBtn.addActionListener(this::jIngresarBtnActionPerformed);
        jPanel1.add(jIngresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 440, 50));

        jCancelarBtn.setBackground(new java.awt.Color(51, 153, 255));
        jCancelarBtn.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jCancelarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jCancelarBtn.setText("Cancelar");
        jCancelarBtn.addActionListener(this::jCancelarBtnActionPerformed);
        jPanel1.add(jCancelarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 440, 50));

        jViewPasswordBtn.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jViewPasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        jViewPasswordBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password_hide.png"))); // NOI18N
        jViewPasswordBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jViewPasswordBtn.setBorderPainted(false);
        jViewPasswordBtn.setContentAreaFilled(false);
        jViewPasswordBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jViewPasswordBtn.addActionListener(this::jViewPasswordBtnActionPerformed);
        jPanel1.add(jViewPasswordBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 240, -1, 20));

        jPasswordField.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jPasswordField.addActionListener(this::jPasswordFieldActionPerformed);
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 440, 40));

        jProgressBar.setBackground(new java.awt.Color(50, 50, 50));
        jProgressBar.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jProgressBar.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(jProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 500, 30));

        jMenLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jMenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jPanel1.add(jMenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 40, -1));

        jKeyLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jKeyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jKeyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key.png"))); // NOI18N
        jPanel1.add(jKeyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jIngresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIngresarBtnActionPerformed
        // TODO add your handling code here:
        String user = jUsernameField.getText().trim();
        String pass = new String(jPasswordField.getPassword());

        if (user.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingresa usuario y contraseña!");
            return;
        }

        if (user.equals("admin") && pass.equals("1234")) {
            intentos = 0;
            jIngresarBtn.setEnabled(false);
            jCancelarBtn.setEnabled(false);
            iniciarProgressBar();
            bloquearBoton();
        } else {
            intentos++;
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas. Intento " + intentos + "/3");
            jUsernameField.setText("");
            jPasswordField.setText("");
            if (intentos >= 3) {
                bloquearBoton();
            }
        }
    }//GEN-LAST:event_jIngresarBtnActionPerformed

    private void jCancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelarBtnActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que quieres salir?",
            "Cerrar sesión",
            JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            new LoginView().setVisible(true);
            System.exit(0);
        }
    }//GEN-LAST:event_jCancelarBtnActionPerformed

    private void jViewPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewPasswordBtnActionPerformed
        // TODO add your handling code here:
        if (passwordVisible) {
            // ocultar contraseña
            jPasswordField.setEchoChar('•');

            jViewPasswordBtn.setIcon(
                    new ImageIcon(getClass().getResource("/icons/password_hide.png"))
            );

            passwordVisible = false;
        } else {
            // mostrar contraseña
            jPasswordField.setEchoChar((char) 0);

            jViewPasswordBtn.setIcon(
                    new ImageIcon(getClass().getResource("/icons/password_view.png"))
            );

            passwordVisible = true;
        }
    }//GEN-LAST:event_jViewPasswordBtnActionPerformed

    private void iniciarProgressBar() {
    jProgressBar.setValue(0);
        jProgressBar.setString("");
        jProgressBar.setStringPainted(true);

        Timer timer = new Timer(20, null);

        timer.addActionListener(new ActionListener() {
            private int value = 0;
            private final int total = 100;

            @Override
            public void actionPerformed(ActionEvent e) {
                value += 1;

                jProgressBar.setValue(value);

                if (value >= total) {
                    ((Timer) e.getSource()).stop();

                    SwingUtilities.invokeLater(() -> {
                        new Pnl_menu_principal().setVisible(true);
                        dispose();
                    });
                }
            }
        });

        timer.start();
    }

    private void bloquearBoton() {
        jIngresarBtn.setEnabled(false);
        jUsernameField.setEnabled(false);
        jPasswordField.setEnabled(false);
        jViewPasswordBtn.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());  // Tema oscuro (recomendado)
            UIManager.put("Button.arc", 12);              // botones más redondeados
            UIManager.put("Component.arc", 10);           // componentes en general
            UIManager.put("TextComponent.arc", 10);       // campos de texto redondeados

            // Color de acento más bonito (azul brillante moderno)
            UIManager.put("Component.accentColor", new java.awt.Color(59, 130, 246)); // azul #3b82f6

            // Otras opciones:
            // UIManager.setLookAndFeel(new FlatLightLaf());
            // UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            System.err.println("Error al aplicar FlatLaf: " + ex.getMessage());
        }
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelarBtn;
    private javax.swing.JButton jIngresarBtn;
    private javax.swing.JLabel jInicioLabel;
    private javax.swing.JLabel jInicioLabel2;
    private javax.swing.JLabel jKeyLabel;
    private javax.swing.JLabel jMenLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JButton jViewPasswordBtn;
    // End of variables declaration//GEN-END:variables

    private Icon getIconUrl(String url, int w, int h) {
        return new ImageIcon(new ImageIcon(getClass().getResource(url))
                .getImage().getScaledInstance(w, h, 0));
    }
}
