/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import utilerias.ConexionBD;

/**
 *
 * @author Contrerasalexa1907
 */
public class Pnl_lavanderia extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_nivel_de_agua
     */
    public Pnl_lavanderia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKilos = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIVEL DE AGUA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RESULTADO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtKilos.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtKilos.addActionListener(this::txtKilosActionPerformed);
        jPanel1.add(txtKilos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        btnLimpiar.setBackground(new java.awt.Color(184, 224, 210));
        btnLimpiar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CANTIDAD DE ROPA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnMostrar.setBackground(new java.awt.Color(128, 155, 206));
        btnMostrar.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lavadora.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 260, 320));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 290, 140));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));
    }// </editor-fold>//GEN-END:initComponents

    public void guardarHistorialAgua(double kilos, String nivel, double litros) {
        ConexionBD con = new ConexionBD();
        String sql = "INSERT INTO historial_agua (kilos, nivel, litros) VALUES (?, ?, ?)";

        try (java.sql.Connection cn = con.conectar();
             java.sql.PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setDouble(1, kilos);
            ps.setString(2, nivel);
            ps.setDouble(3, litros); // Aquí puedes pasar los litros calcula    dos

            ps.executeUpdate();
            System.out.println("Registro de agua guardado con éxito.");

        } catch (java.sql.SQLException e) {
            System.err.println("Error al guardar historial de agua: " + e.getMessage());
        }
    }
    
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        btnMostrar.addActionListener(e -> {
            try {
                // 1. VALIDACIÓN: Verificar si hay texto antes de procesar
                if (txtKilos.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Por favor, ingresa los kilos.");
                    return;
                }

                double kilos = Double.parseDouble(txtKilos.getText());
                String mensaje = "";
                double litrosCalculados = kilos * 2; // Ejemplo de lógica: 2 litros por kilo

                // 2. LÓGICA: Determinar nivel
                if (kilos > 30) mensaje = "DEMASIADO PESO";
                else if (kilos >= 22) mensaje = "MAXIMO";
                else if (kilos >= 15) mensaje = "ALTO";
                else if (kilos >= 8) mensaje = "MEDIO";
                else mensaje = "MINIMO";

                // 3. MOSTRAR: Resultado en el TextArea
                txtR.setText("");
                txtR.append("Kilos: " + kilos);
                txtR.append("\nNivel de Agua es: " + mensaje);
                txtR.append("\nLitros aproximados: " + litrosCalculados);

                // 4. GUARDAR: Enviar a la base de datos automáticamente
                guardarHistorialAgua(kilos, mensaje, litrosCalculados);

                // OPCIONAL: Si tienes un JTable para esto, llámalo aquí para refrescar
                // consultarHistorialAgua();

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Error: Ingresa un número válido para los kilos.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error inesperado: " + ex.getMessage());
            }
        });
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtKilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        btnLimpiar.addActionListener(e -> {
            txtKilos.setText("");
            txtR.setText("");
            txtKilos.requestFocus();
        });
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtKilos;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
