/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import utilerias.ConexionBD;

/**
 *
 * @author Gilberto
 */
public class Pnl_casa_cambio extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    
    public Pnl_casa_cambio() {
        initComponents();
        // PASO NUEVO: Carga los datos de la BD al abrir la ventana
        sincronizarPrecios();  // Llena los cuadros de Dólar y Marco
        consultarHistorial();  // Llena tu JTable con el historial
    }
    
    public void sincronizarPrecios() {
    try {
        // 1. Conectamos usando tu clase
        ConexionBD con = new ConexionBD();
        // 2. Pedimos los precios (Asegúrate de haber creado la tabla en phpMyAdmin)
        try (Connection cn = con.conectar()) {
            // 2. Pedimos los precios (Asegúrate de haber creado la tabla en phpMyAdmin)
            String sql = "SELECT moneda, precio FROM tipos_cambio";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            // 3. Llenamos los campos automáticamente
            while (rs.next()) {
                String moneda = rs.getString("moneda");
                String precio = rs.getString("precio");
                
                if (moneda.equalsIgnoreCase("Dolar")) {
                    jDolaresField.setText(precio);
                }
                if (moneda.equalsIgnoreCase("Marco")) {
                    jMarcosField.setText(precio);
                }
            }
        }
    } catch (SQLException e) {
        System.err.println("Error de sincronización: " + e.getMessage());
    }
    }
    
    /**
     *
     * @param soles
     * @param precioDolar
     * @param precioMarco
     * @param montoTotal
     */
    
     // Método para guardar los datos de entrada y el resultado en MySQL
    public void guardarEnBD(double s, double d, double m, double total) {
        ConexionBD con = new ConexionBD();
        String sql = "INSERT INTO historial_operaciones (monto_soles, cambio_dolar, cambio_marco, total_euros) VALUES (?, ?, ?, ?)";

        try (java.sql.Connection cn = con.conectar();
             java.sql.PreparedStatement ps = cn.prepareStatement(sql)) {

            ps.setDouble(1, s);
            ps.setDouble(2, d);
            ps.setDouble(3, m);
            ps.setDouble(4, total);

            ps.executeUpdate(); // Ejecuta la inserción
            System.out.println("Registro guardado en el historial con éxito.");

        } catch (java.sql.SQLException e) {
            System.err.println("Error al guardar: " + e.getMessage());
        }
    }
    
    public void consultarHistorial() {
        ConexionBD con = new ConexionBD();
        String sql = "SELECT * FROM historial_operaciones ORDER BY fecha_registro DESC";

        // Definimos las columnas de la tabla
        String[] columnas = {"ID", "Soles", "Dólar", "Marco", "Total Euros", "Fecha"};
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, columnas);

        try (java.sql.Connection cn = con.conectar();
             java.sql.Statement st = cn.createStatement();
             java.sql.ResultSet rs = st.executeQuery(sql)) {

            String[] fila = new String[6];
            while (rs.next()) {
                fila[0] = rs.getString("id");
                fila[1] = rs.getString("monto_soles");
                fila[2] = rs.getString("cambio_dolar");
                fila[3] = rs.getString("cambio_marco");
                fila[4] = rs.getString("total_euros");
                fila[5] = rs.getString("fecha_registro");
                modelo.addRow(fila);
            }
            tblHistorial.setModel(modelo); // Asignamos los datos a tu JTable

        } catch (java.sql.SQLException e) {
            System.err.println("Error al consultar historial: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSolesLabel = new javax.swing.JLabel();
        jDolaresLabel = new javax.swing.JLabel();
        jMarcosLabel = new javax.swing.JLabel();
        jTitulo = new javax.swing.JLabel();
        jMarcosField = new javax.swing.JTextField();
        jSolesField = new javax.swing.JTextField();
        jDolaresField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jResumenArea = new javax.swing.JTextArea();
        jLimpiarBtn = new javax.swing.JButton();
        jMostrarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jSolesLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jSolesLabel.setForeground(new java.awt.Color(255, 255, 255));
        jSolesLabel.setText("VALOR EN SOLES");

        jDolaresLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jDolaresLabel.setForeground(new java.awt.Color(255, 255, 255));
        jDolaresLabel.setText("VALOR EN DOLARES");

        jMarcosLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jMarcosLabel.setForeground(new java.awt.Color(255, 255, 255));
        jMarcosLabel.setText("VALOR EN MARCOS");

        jTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jTitulo.setText("CASA DE CAMBIO");

        jMarcosField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMarcosField.setToolTipText("");

        jSolesField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jDolaresField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jResumenArea.setColumns(20);
        jResumenArea.setRows(5);
        jScrollPane1.setViewportView(jResumenArea);

        jLimpiarBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLimpiarBtn.setText("LIMPIAR");
        jLimpiarBtn.addActionListener(this::jLimpiarBtnActionPerformed);

        jMostrarBtn.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jMostrarBtn.setText("MOSTRAR");
        jMostrarBtn.addActionListener(this::jMostrarBtnActionPerformed);

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblHistorial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLimpiarBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jMostrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSolesLabel)
                            .addComponent(jDolaresLabel)
                            .addComponent(jMarcosLabel))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMarcosField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDolaresField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSolesField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTitulo)
                .addGap(215, 215, 215))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jTitulo)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSolesLabel)
                    .addComponent(jSolesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDolaresLabel)
                    .addComponent(jDolaresField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMarcosLabel)
                    .addComponent(jMarcosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLimpiarBtn)
                    .addComponent(jMostrarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jMostrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMostrarBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource()==jMostrarBtn) {
            
            double soles = Double.parseDouble(jSolesField.getText());
            double dolares = Double.parseDouble(jDolaresField.getText());
            double marcos = Double.parseDouble(jMarcosField.getText());
            
            double montoTotal = (soles / dolares + soles / marcos) * 1.09;
            
            String resultado = String.format("%.2f", montoTotal);
            jResumenArea.setText(" ** RESUMEN DE CASA DE CAMBIO ** ");
            jResumenArea.append("\n");
            jResumenArea.append("\nEL MONTO TOTAL EN EUROS ES: " + resultado);
            
            // 4. GUARDAR: Enviar a la base de datos (Lo haremos en el siguiente paso)
            guardarEnBD(soles, dolares, marcos, montoTotal);
            //  PASO NUEVO: Refresca la tabla para ver el nuevo registro inmediatamente
            consultarHistorial();
        }
    }//GEN-LAST:event_jMostrarBtnActionPerformed

    private void jLimpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLimpiarBtnActionPerformed
        // TODO add your handling code here:
        if (evt.getSource()==jLimpiarBtn) {
            jSolesField.setText("");
            jDolaresField.setText("");
            jMarcosField.setText("");
            jResumenArea.setText("");
            
        }
    }//GEN-LAST:event_jLimpiarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jDolaresField;
    private javax.swing.JLabel jDolaresLabel;
    private javax.swing.JButton jLimpiarBtn;
    private javax.swing.JTextField jMarcosField;
    private javax.swing.JLabel jMarcosLabel;
    private javax.swing.JButton jMostrarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jResumenArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jSolesField;
    private javax.swing.JLabel jSolesLabel;
    private javax.swing.JLabel jTitulo;
    private javax.swing.JTable tblHistorial;
    // End of variables declaration//GEN-END:variables

}