/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import vistas.LoginView;
import java.awt.CardLayout;
import java.sql.Connection;
import java.time.LocalDateTime;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import vistas.Pnl_casa_cambio;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import utilerias.ConexionBD;

/**
 *
 * @author Gilberto
 */
public class Pnl_menu_principal extends javax.swing.JFrame {
    
    Pnl_casa_cambio pnl_casa_cambio = new Pnl_casa_cambio();
    Pnl_consumo_de_agua pnl_consumo_de_agua = new Pnl_consumo_de_agua();
    Pnl_lavanderia pnl_lavanderia = new Pnl_lavanderia();
    Pnl_hectareas pnl_hectareas = new Pnl_hectareas();
    Pnl_pago_empleados pnl_pago_empleados = new Pnl_pago_empleados();
    
    CardLayout vista;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pnl_menu_principal.class.getName());

    /**
     * Creates new form menuprincipal
     */
    public Pnl_menu_principal() {
        initComponents();
        mostrarBienvenida();
        setIconImage(new ImageIcon(getClass().getResource("/icons/coding.png")).getImage());
        this.setTitle("Menu de Programas - Equipo 4");
        vista = (CardLayout) pnl_vista_principal.getLayout();
        verificarConexion();
    }
    
        void verificarConexion() {

        try {
            ConexionBD cn = new ConexionBD();
            Connection con = cn.conectar();

            if (con != null && !con.isClosed()) {

                jConexionLabel.setText("Conectado");

                jConexionEstadoLogo.setIcon(
                    new ImageIcon(getClass().getResource("/icons/bd_on.png"))
                );

                con.close();
            }

        } catch (Exception e) {

            jConexionLabel.setText("Sin conexión");

            jConexionEstadoLogo.setIcon(
                new ImageIcon(getClass().getResource("/icons/bd_off.png"))
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTituloLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTituloSistema = new javax.swing.JLabel();
        jHectareasLogo3 = new javax.swing.JLabel();
        jConsumoAguaLogo2 = new javax.swing.JLabel();
        jLavanderiaLogo1 = new javax.swing.JLabel();
        jPagoEmpleadosLogo = new javax.swing.JLabel();
        jCasaCambioLogo = new javax.swing.JLabel();
        jPagoEmpleadosBtn = new javax.swing.JButton();
        jCasaCambioBtn = new javax.swing.JButton();
        jLavanderiaBtn = new javax.swing.JButton();
        jConsumoAguaBtn = new javax.swing.JButton();
        jHectareasBtn = new javax.swing.JButton();
        jCerrarSesionBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jConexionLabel = new javax.swing.JLabel();
        jConexionEstadoLogo = new javax.swing.JLabel();
        pnl_vista_principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jProgramas = new javax.swing.JMenu();
        jCasaCambioItem = new javax.swing.JMenuItem();
        jPagoEmpleadosItem = new javax.swing.JMenuItem();
        jLavanderiaItem = new javax.swing.JMenuItem();
        jConsumoAguaItem = new javax.swing.JMenuItem();
        jHectareasItem = new javax.swing.JMenuItem();
        jConsultas = new javax.swing.JMenu();
        jConsultarRegistrosItem = new javax.swing.JMenuItem();
        jConsultarRegistroIDItem = new javax.swing.JMenuItem();
        jReportes = new javax.swing.JMenu();
        jAyuda = new javax.swing.JMenu();
        jAcercaDeItem = new javax.swing.JMenuItem();
        jManualUsuarioItem = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        jCerrarSesionItem = new javax.swing.JMenuItem();
        jSalirItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTituloLabel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        jTituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTituloLabel.setText("¡Bienvenido, Usuario | 10/04/2026 - 11:57 P.M");
        jPanel1.add(jTituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 900, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel3.setBackground(new java.awt.Color(30, 30, 30));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTituloSistema.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jTituloSistema.setForeground(new java.awt.Color(255, 255, 255));
        jTituloSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTituloSistema.setText("Menu del Sistema");
        jPanel3.add(jTituloSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 40, 180, -1));

        jHectareasLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cotton.png"))); // NOI18N
        jHectareasLogo3.setDoubleBuffered(true);
        jHectareasLogo3.setMaximumSize(new java.awt.Dimension(64, 64));
        jHectareasLogo3.setMinimumSize(new java.awt.Dimension(64, 64));
        jHectareasLogo3.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jHectareasLogo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 50, 50));

        jConsumoAguaLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/water.png"))); // NOI18N
        jConsumoAguaLogo2.setDoubleBuffered(true);
        jConsumoAguaLogo2.setMaximumSize(new java.awt.Dimension(64, 64));
        jConsumoAguaLogo2.setMinimumSize(new java.awt.Dimension(64, 64));
        jConsumoAguaLogo2.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jConsumoAguaLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 50, 50));

        jLavanderiaLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/laundry.png"))); // NOI18N
        jLavanderiaLogo1.setDoubleBuffered(true);
        jLavanderiaLogo1.setMaximumSize(new java.awt.Dimension(64, 64));
        jLavanderiaLogo1.setMinimumSize(new java.awt.Dimension(64, 64));
        jLavanderiaLogo1.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jLavanderiaLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 50, 50));

        jPagoEmpleadosLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employee_pay.png"))); // NOI18N
        jPagoEmpleadosLogo.setDoubleBuffered(true);
        jPagoEmpleadosLogo.setMaximumSize(new java.awt.Dimension(64, 64));
        jPagoEmpleadosLogo.setMinimumSize(new java.awt.Dimension(64, 64));
        jPagoEmpleadosLogo.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jPagoEmpleadosLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 50, 50));

        jCasaCambioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/house_change.png"))); // NOI18N
        jCasaCambioLogo.setDoubleBuffered(true);
        jCasaCambioLogo.setMaximumSize(new java.awt.Dimension(64, 64));
        jCasaCambioLogo.setMinimumSize(new java.awt.Dimension(64, 64));
        jCasaCambioLogo.setPreferredSize(new java.awt.Dimension(64, 64));
        jPanel3.add(jCasaCambioLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 50, 50));

        jPagoEmpleadosBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPagoEmpleadosBtn.setText("Pago de Empleados");
        jPagoEmpleadosBtn.setToolTipText("");
        jPagoEmpleadosBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPagoEmpleadosBtn.addActionListener(this::jPagoEmpleadosBtnActionPerformed);
        jPanel3.add(jPagoEmpleadosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 90));

        jCasaCambioBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jCasaCambioBtn.setText("Casa de Cambio");
        jCasaCambioBtn.setToolTipText("");
        jCasaCambioBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jCasaCambioBtn.addActionListener(this::jCasaCambioBtnActionPerformed);
        jPanel3.add(jCasaCambioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 90));

        jLavanderiaBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLavanderiaBtn.setText("Lavandería");
        jLavanderiaBtn.setToolTipText("");
        jLavanderiaBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLavanderiaBtn.addActionListener(this::jLavanderiaBtnActionPerformed);
        jPanel3.add(jLavanderiaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 180, 90));

        jConsumoAguaBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jConsumoAguaBtn.setText("Consumo de Agua");
        jConsumoAguaBtn.setToolTipText("");
        jConsumoAguaBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jConsumoAguaBtn.addActionListener(this::jConsumoAguaBtnActionPerformed);
        jPanel3.add(jConsumoAguaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, 90));

        jHectareasBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jHectareasBtn.setText("Hectáreas de algodón");
        jHectareasBtn.setToolTipText("");
        jHectareasBtn.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jHectareasBtn.addActionListener(this::jHectareasBtnActionPerformed);
        jPanel3.add(jHectareasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 180, 90));

        jCerrarSesionBtn.setText("Cerrar Sesión");
        jCerrarSesionBtn.addActionListener(this::jCerrarSesionBtnActionPerformed);
        jPanel3.add(jCerrarSesionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jConexionLabel.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jConexionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConexionLabel.setText("Sin Conexion");
        jPanel4.add(jConexionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 140, 30));

        jConexionEstadoLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jConexionEstadoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bd_off.png"))); // NOI18N
        jPanel4.add(jConexionEstadoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 30, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 200, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 640));

        pnl_vista_principal.setBackground(new java.awt.Color(50, 50, 50));
        pnl_vista_principal.setToolTipText("");
        pnl_vista_principal.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnl_vista_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 700, 600));

        jMenuBar1.setBackground(new java.awt.Color(30, 136, 229));
        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);

        jProgramas.setText("Programas");

        jCasaCambioItem.setText("Casa de Cambio");
        jCasaCambioItem.addActionListener(this::jCasaCambioItemActionPerformed);
        jProgramas.add(jCasaCambioItem);

        jPagoEmpleadosItem.setText("Pago de Empleados");
        jPagoEmpleadosItem.addActionListener(this::jPagoEmpleadosItemActionPerformed);
        jProgramas.add(jPagoEmpleadosItem);

        jLavanderiaItem.setText("Lavanderia");
        jLavanderiaItem.addActionListener(this::jLavanderiaItemActionPerformed);
        jProgramas.add(jLavanderiaItem);

        jConsumoAguaItem.setText("Consumo de Agua");
        jConsumoAguaItem.addActionListener(this::jConsumoAguaItemActionPerformed);
        jProgramas.add(jConsumoAguaItem);

        jHectareasItem.setText("Hectáreas de algodón");
        jHectareasItem.addActionListener(this::jHectareasItemActionPerformed);
        jProgramas.add(jHectareasItem);

        jMenuBar1.add(jProgramas);

        jConsultas.setText("Consultas");

        jConsultarRegistrosItem.setText("Consultar registros (por programa)");
        jConsultas.add(jConsultarRegistrosItem);

        jConsultarRegistroIDItem.setText("Buscar registro");
        jConsultas.add(jConsultarRegistroIDItem);

        jMenuBar1.add(jConsultas);

        jReportes.setText("Reportes");
        jMenuBar1.add(jReportes);

        jAyuda.setText("Ayuda");

        jAcercaDeItem.setText("Acerca de");
        jAcercaDeItem.addActionListener(this::jAcercaDeItemActionPerformed);
        jAyuda.add(jAcercaDeItem);

        jManualUsuarioItem.setText("Manual de Usuario");
        jManualUsuarioItem.addActionListener(this::jManualUsuarioItemActionPerformed);
        jAyuda.add(jManualUsuarioItem);

        jMenuBar1.add(jAyuda);

        jSalir.setText("Salir");

        jCerrarSesionItem.setText("Cerrar sesión");
        jCerrarSesionItem.addActionListener(this::jCerrarSesionItemActionPerformed);
        jSalir.add(jCerrarSesionItem);

        jSalirItem.setText("Salir de la aplicación");
        jSalirItem.addActionListener(this::jSalirItemActionPerformed);
        jSalir.add(jSalirItem);

        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarBienvenida() {
        LocalDateTime ahora = LocalDateTime.now();

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy hh:mm a");

        String mensaje = "¡Bienvenido, Usuario" + " | " + ahora.format(formato);

        jTituloLabel.setText(mensaje);
    }
    
    private void jPagoEmpleadosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagoEmpleadosBtnActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_pago_empleados)) {

            pnl_vista_principal.add(pnl_pago_empleados, "Pago de Empleados");
        }

        vista.show(pnl_vista_principal, "Pago de Empleados");

        // Forzar revalidación y redibujado
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jPagoEmpleadosBtnActionPerformed

    private void jCasaCambioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCasaCambioBtnActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_casa_cambio)) {

            pnl_vista_principal.add(pnl_casa_cambio, "Casa de Cambio");
        }

        vista.show(pnl_vista_principal, "Casa de Cambio");

        // Forzar revalidación y redibujado
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jCasaCambioBtnActionPerformed

    private void jLavanderiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLavanderiaBtnActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_lavanderia)) {

            pnl_vista_principal.add(pnl_lavanderia, "Lavanderia");
        }

        vista.show(pnl_vista_principal, "Lavanderia");

        // Forzar revalidación y redibujado
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jLavanderiaBtnActionPerformed

    private void jConsumoAguaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsumoAguaBtnActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_consumo_de_agua)) {

            pnl_vista_principal.add(pnl_consumo_de_agua, "Consumo de Agua");
        }

        vista.show(pnl_vista_principal, "Consumo de Agua");

        // Forzar revalidación y redibujado
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jConsumoAguaBtnActionPerformed

    private void jHectareasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHectareasBtnActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_hectareas)) {

            pnl_vista_principal.add(pnl_hectareas, "Hectareas");
        }

        vista.show(pnl_vista_principal, "Hectareas");

        // Forzar revalidación y redibujado
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jHectareasBtnActionPerformed

    private void jAcercaDeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcercaDeItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Esta aplicación fue desarrollada por el Equipo 4 \n- Cambron Escobar Guillermo \n- Contreras Juarez Ezry Alexandra \n- Erika Ramírez Chavarría \n- Lisset Isidro Sanchez \n- Génesis Nerina García Contreras");
    }//GEN-LAST:event_jAcercaDeItemActionPerformed

    private void jManualUsuarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jManualUsuarioItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jManualUsuarioItemActionPerformed

    private void jCerrarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCerrarSesionBtnActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que deseas cerrar sesión?",
            "Cerrar sesión",
            JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            new LoginView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCerrarSesionBtnActionPerformed

    private void jCasaCambioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCasaCambioItemActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_casa_cambio)) {

            pnl_vista_principal.add(pnl_casa_cambio, "Casa de Cambio");
        }

        vista.show(pnl_vista_principal, "Casa de Cambio");

        // Forzar revalidación y redibujado
        pnl_vista_principal.revalidate();
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jCasaCambioItemActionPerformed

    private void jCerrarSesionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCerrarSesionItemActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Seguro que deseas cerrar sesión?",
            "Cerrar sesión",
            JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            new LoginView().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jCerrarSesionItemActionPerformed

    private void jSalirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jSalirItemActionPerformed

    private void jPagoEmpleadosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagoEmpleadosItemActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_pago_empleados)) {

            pnl_vista_principal.add(pnl_pago_empleados, "Pago de Empleados");
        }

        vista.show(pnl_vista_principal, "Pago de Empleados");

        // Forzar revalidación y redibujado
        pnl_vista_principal.revalidate();
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jPagoEmpleadosItemActionPerformed

    private void jLavanderiaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLavanderiaItemActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_lavanderia)) {

            pnl_vista_principal.add(pnl_lavanderia, "Lavanderia");
        }

        vista.show(pnl_vista_principal, "Lavanderia");

        // Forzar revalidación y redibujado
        pnl_vista_principal.revalidate();
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jLavanderiaItemActionPerformed

    private void jConsumoAguaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsumoAguaItemActionPerformed
        // Si el panel aún no ha sido agregado, lo agregamos una sola vez
        if (pnl_vista_principal.getComponentCount() == 0 || 
            !java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_consumo_de_agua)) {

            pnl_vista_principal.add(pnl_consumo_de_agua, "Consumo de Agua");
        }

        vista.show(pnl_vista_principal, "Consumo de Agua");

        // Forzar revalidación y redibujado
        pnl_vista_principal.revalidate();
        pnl_vista_principal.repaint();

        // Opcional: ajustar el JFrame
        this.pack();
    }//GEN-LAST:event_jConsumoAguaItemActionPerformed

    private void jHectareasItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHectareasItemActionPerformed
        if (!java.util.Arrays.asList(pnl_vista_principal.getComponents()).contains(pnl_hectareas)) {
            pnl_vista_principal.add(pnl_hectareas, "Hectareas");
        }

        vista.show(pnl_vista_principal, "Hectareas");

        pnl_vista_principal.revalidate();
        pnl_vista_principal.repaint();

        this.pack();
    }//GEN-LAST:event_jHectareasItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pnl_menu_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jAcercaDeItem;
    private javax.swing.JMenu jAyuda;
    private javax.swing.JButton jCasaCambioBtn;
    private javax.swing.JMenuItem jCasaCambioItem;
    private javax.swing.JLabel jCasaCambioLogo;
    private javax.swing.JButton jCerrarSesionBtn;
    private javax.swing.JMenuItem jCerrarSesionItem;
    private javax.swing.JLabel jConexionEstadoLogo;
    private javax.swing.JLabel jConexionLabel;
    private javax.swing.JMenuItem jConsultarRegistroIDItem;
    private javax.swing.JMenuItem jConsultarRegistrosItem;
    private javax.swing.JMenu jConsultas;
    private javax.swing.JButton jConsumoAguaBtn;
    private javax.swing.JMenuItem jConsumoAguaItem;
    private javax.swing.JLabel jConsumoAguaLogo2;
    private javax.swing.JButton jHectareasBtn;
    private javax.swing.JMenuItem jHectareasItem;
    private javax.swing.JLabel jHectareasLogo3;
    private javax.swing.JButton jLavanderiaBtn;
    private javax.swing.JMenuItem jLavanderiaItem;
    private javax.swing.JLabel jLavanderiaLogo1;
    private javax.swing.JMenuItem jManualUsuarioItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jPagoEmpleadosBtn;
    private javax.swing.JMenuItem jPagoEmpleadosItem;
    private javax.swing.JLabel jPagoEmpleadosLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenu jProgramas;
    private javax.swing.JMenu jReportes;
    private javax.swing.JMenu jSalir;
    private javax.swing.JMenuItem jSalirItem;
    private javax.swing.JLabel jTituloLabel;
    private javax.swing.JLabel jTituloSistema;
    private javax.swing.JPanel pnl_vista_principal;
    // End of variables declaration//GEN-END:variables
}
