/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Contrerasalexa1907
 */
public class Pnl_consumo_de_agua extends javax.swing.JPanel {

    /**
     * Creates new form Pnl_consumo_de_agua
     */
    public Pnl_consumo_de_agua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtConsumo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TOTAL DE METROS CUBICOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 98, -1, -1));

        txtConsumo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 126, 278, 60));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("RESUMEN DE CONSUMO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        txtR.setColumns(20);
        txtR.setRows(5);
        jScrollPane1.setViewportView(txtR);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 278, 100));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/consumo_agua.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 80, 380, 520));

        btnCalcular.setBackground(new java.awt.Color(255, 215, 0));
        btnCalcular.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(50, 205, 50));
        btnLimpiar.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, -1));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONSUMO DE AGUA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {

            if (txtConsumo.getText().trim().isEmpty()) { // Verifica si está vacío
                JOptionPane.showMessageDialog(this, "Ingresa un valor de consumo"); // Muestra mensaje
                txtConsumo.requestFocus(); // Regresa foco
                return; // Detiene ejecución
            }

            double consumo = Double.parseDouble(txtConsumo.getText()); // Convierte texto a número

            if (consumo < 0) { // Verifica valores negativos
                JOptionPane.showMessageDialog(this, "No se permiten valores negativos"); // Error
                txtConsumo.setText(""); // Limpia campo
                txtConsumo.requestFocus(); // Regresa foco
                return; // Detiene ejecución
            }

            double monto = 0; // Inicializa monto

            if (consumo < 100) { // Primer rango
                monto = 0.15 * consumo;
            } else if (consumo >= 100 && consumo < 500) { // Segundo rango
                monto = 0.2 * consumo;
            } else if (consumo >= 500 && consumo < 1000) { // Tercer rango
                monto = 0.35 * consumo;
            } else { // Último rango
                monto = 0.8 * consumo;
            }

            double impuesto = 0; // Inicializa impuesto

            if (monto > 600) { // Aplica impuesto si supera 600
                impuesto = 2.5 / 100 * monto;
            }

            monto = monto + impuesto; // Suma impuesto al monto

            txtR.setText(""); // Limpia área
            txtR.append("Consumo m3 es : " + consumo); // Muestra consumo
            txtR.append("\nEl impuesto es: $" + String.format("%.2f", impuesto)); // Muestra impuesto
            txtR.append("\nEl monto a pagar es: $" + String.format("%.2f", monto)); // Muestra total

            Connection con = DriverManager.getConnection( // Conexión BD
                    "jdbc:mysql://localhost:3306/db_casacambio",
                    "root",
                    ""
            );

            PreparedStatement ps = con.prepareStatement( // Inserta datos
                    "INSERT INTO consumo_agua (consumo, monto, impuesto, total) VALUES (?, ?, ?, ?)"
            );

            ps.setDouble(1, consumo); // Parámetro consumo
            ps.setDouble(2, monto); // Parámetro monto
            ps.setDouble(3, impuesto); // Parámetro impuesto
            ps.setDouble(4, monto); // Parámetro total

            ps.executeUpdate(); // Ejecuta inserción

            Statement st = con.createStatement(); // Crea statement

            ResultSet rs = st.executeQuery("SELECT * FROM consumo_agua"); // Consulta datos

            String datos = ""; // Cadena acumuladora

            while (rs.next()) { // Recorre resultados
                datos += rs.getInt("id") + " - "
                        + String.format("%.2f", rs.getDouble("consumo")) + " - "
                        + String.format("%.2f", rs.getDouble("monto")) + "\n"; // Construye texto
            }

            txtR.setText(datos); // Muestra datos en pantalla

        } catch (Exception e) { // Manejo de errores
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage()); // Muestra error
            txtConsumo.setText(""); // Limpia campo
            txtConsumo.requestFocus(); // Regresa foco
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtConsumo.setText(""); // Limpia campo consumo
        txtR.setText(""); // Limpia resultados
        txtConsumo.requestFocus(); // Regresa foco        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtConsumo;
    private javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
